{#-
    Kaggle's hidden test set: same columns as application_train except TARGET (unknown, so these
    clients can never enter a default-rate calculation). Kept because related tables (bureau,
    previous_application, ...) also hold records of these clients.
-#}

with source as (

    select * from {{ source('raw', 'application_test') }}

),

typed as (

    select
        {{ to_bigint('sk_id_curr') }} as sk_id_curr,
        {{ clean_text('name_contract_type') }} as name_contract_type,
        {{ null_if_xna('code_gender') }} as code_gender,
        {{ is_xna('code_gender') }} as is_code_gender_xna,
        {{ to_bool_yn('flag_own_car') }} as flag_own_car,
        {{ to_bool_yn('flag_own_realty') }} as flag_own_realty,
        {{ to_bigint('cnt_children') }} as cnt_children,
        {{ to_decimal('amt_income_total') }} as amt_income_total,
        {{ to_decimal('amt_credit') }} as amt_credit,
        {{ to_decimal('amt_annuity') }} as amt_annuity,
        {{ to_decimal('amt_goods_price') }} as amt_goods_price,
        {{ clean_text('name_type_suite') }} as name_type_suite,
        {{ clean_text('name_income_type') }} as name_income_type,
        {{ clean_text('name_education_type') }} as name_education_type,
        {{ clean_text('name_family_status') }} as name_family_status,
        {{ clean_text('name_housing_type') }} as name_housing_type,
        {{ to_double('region_population_relative') }} as region_population_relative,
        {{ to_bigint('days_birth') }} as days_birth,
        {{ null_if_sentinel('days_employed') }} as days_employed,
        {{ is_sentinel('days_employed') }} as is_days_employed_sentinel,
        {{ to_double('days_registration') }} as days_registration,
        {{ to_bigint('days_id_publish') }} as days_id_publish,
        {{ to_bigint('own_car_age') }} as own_car_age,
        {{ to_bool_01('flag_mobil') }} as flag_mobil,
        {{ to_bool_01('flag_emp_phone') }} as flag_emp_phone,
        {{ to_bool_01('flag_work_phone') }} as flag_work_phone,
        {{ to_bool_01('flag_cont_mobile') }} as flag_cont_mobile,
        {{ to_bool_01('flag_phone') }} as flag_phone,
        {{ to_bool_01('flag_email') }} as flag_email,
        {{ clean_text('occupation_type') }} as occupation_type,
        {{ to_bigint('cnt_fam_members') }} as cnt_fam_members,
        {{ to_bigint('region_rating_client') }} as region_rating_client,
        {{ to_bigint('region_rating_client_w_city') }} as region_rating_client_w_city,
        {{ clean_text('weekday_appr_process_start') }} as weekday_appr_process_start,
        {{ to_bigint('hour_appr_process_start') }} as hour_appr_process_start,
        {{ to_bool_01('reg_region_not_live_region') }} as reg_region_not_live_region,
        {{ to_bool_01('reg_region_not_work_region') }} as reg_region_not_work_region,
        {{ to_bool_01('live_region_not_work_region') }} as live_region_not_work_region,
        {{ to_bool_01('reg_city_not_live_city') }} as reg_city_not_live_city,
        {{ to_bool_01('reg_city_not_work_city') }} as reg_city_not_work_city,
        {{ to_bool_01('live_city_not_work_city') }} as live_city_not_work_city,
        {{ null_if_xna('organization_type') }} as organization_type,
        {{ is_xna('organization_type') }} as is_organization_type_xna,
        {{ to_double('ext_source_1') }} as ext_source_1,
        {{ to_double('ext_source_2') }} as ext_source_2,
        {{ to_double('ext_source_3') }} as ext_source_3,
        {{ to_double('apartments_avg') }} as apartments_avg,
        {{ to_double('basementarea_avg') }} as basementarea_avg,
        {{ to_double('years_beginexpluatation_avg') }} as years_beginexpluatation_avg,
        {{ to_double('years_build_avg') }} as years_build_avg,
        {{ to_double('commonarea_avg') }} as commonarea_avg,
        {{ to_double('elevators_avg') }} as elevators_avg,
        {{ to_double('entrances_avg') }} as entrances_avg,
        {{ to_double('floorsmax_avg') }} as floorsmax_avg,
        {{ to_double('floorsmin_avg') }} as floorsmin_avg,
        {{ to_double('landarea_avg') }} as landarea_avg,
        {{ to_double('livingapartments_avg') }} as livingapartments_avg,
        {{ to_double('livingarea_avg') }} as livingarea_avg,
        {{ to_double('nonlivingapartments_avg') }} as nonlivingapartments_avg,
        {{ to_double('nonlivingarea_avg') }} as nonlivingarea_avg,
        {{ to_double('apartments_mode') }} as apartments_mode,
        {{ to_double('basementarea_mode') }} as basementarea_mode,
        {{ to_double('years_beginexpluatation_mode') }} as years_beginexpluatation_mode,
        {{ to_double('years_build_mode') }} as years_build_mode,
        {{ to_double('commonarea_mode') }} as commonarea_mode,
        {{ to_double('elevators_mode') }} as elevators_mode,
        {{ to_double('entrances_mode') }} as entrances_mode,
        {{ to_double('floorsmax_mode') }} as floorsmax_mode,
        {{ to_double('floorsmin_mode') }} as floorsmin_mode,
        {{ to_double('landarea_mode') }} as landarea_mode,
        {{ to_double('livingapartments_mode') }} as livingapartments_mode,
        {{ to_double('livingarea_mode') }} as livingarea_mode,
        {{ to_double('nonlivingapartments_mode') }} as nonlivingapartments_mode,
        {{ to_double('nonlivingarea_mode') }} as nonlivingarea_mode,
        {{ to_double('apartments_medi') }} as apartments_medi,
        {{ to_double('basementarea_medi') }} as basementarea_medi,
        {{ to_double('years_beginexpluatation_medi') }} as years_beginexpluatation_medi,
        {{ to_double('years_build_medi') }} as years_build_medi,
        {{ to_double('commonarea_medi') }} as commonarea_medi,
        {{ to_double('elevators_medi') }} as elevators_medi,
        {{ to_double('entrances_medi') }} as entrances_medi,
        {{ to_double('floorsmax_medi') }} as floorsmax_medi,
        {{ to_double('floorsmin_medi') }} as floorsmin_medi,
        {{ to_double('landarea_medi') }} as landarea_medi,
        {{ to_double('livingapartments_medi') }} as livingapartments_medi,
        {{ to_double('livingarea_medi') }} as livingarea_medi,
        {{ to_double('nonlivingapartments_medi') }} as nonlivingapartments_medi,
        {{ to_double('nonlivingarea_medi') }} as nonlivingarea_medi,
        {{ clean_text('fondkapremont_mode') }} as fondkapremont_mode,
        {{ clean_text('housetype_mode') }} as housetype_mode,
        {{ to_double('totalarea_mode') }} as totalarea_mode,
        {{ clean_text('wallsmaterial_mode') }} as wallsmaterial_mode,
        {{ clean_text('emergencystate_mode') }} as emergencystate_mode,
        {{ to_bigint('obs_30_cnt_social_circle') }} as obs_30_cnt_social_circle,
        {{ to_bigint('def_30_cnt_social_circle') }} as def_30_cnt_social_circle,
        {{ to_bigint('obs_60_cnt_social_circle') }} as obs_60_cnt_social_circle,
        {{ to_bigint('def_60_cnt_social_circle') }} as def_60_cnt_social_circle,
        {{ to_bigint('days_last_phone_change') }} as days_last_phone_change,
        {{ to_bool_01('flag_document_2') }} as flag_document_2,
        {{ to_bool_01('flag_document_3') }} as flag_document_3,
        {{ to_bool_01('flag_document_4') }} as flag_document_4,
        {{ to_bool_01('flag_document_5') }} as flag_document_5,
        {{ to_bool_01('flag_document_6') }} as flag_document_6,
        {{ to_bool_01('flag_document_7') }} as flag_document_7,
        {{ to_bool_01('flag_document_8') }} as flag_document_8,
        {{ to_bool_01('flag_document_9') }} as flag_document_9,
        {{ to_bool_01('flag_document_10') }} as flag_document_10,
        {{ to_bool_01('flag_document_11') }} as flag_document_11,
        {{ to_bool_01('flag_document_12') }} as flag_document_12,
        {{ to_bool_01('flag_document_13') }} as flag_document_13,
        {{ to_bool_01('flag_document_14') }} as flag_document_14,
        {{ to_bool_01('flag_document_15') }} as flag_document_15,
        {{ to_bool_01('flag_document_16') }} as flag_document_16,
        {{ to_bool_01('flag_document_17') }} as flag_document_17,
        {{ to_bool_01('flag_document_18') }} as flag_document_18,
        {{ to_bool_01('flag_document_19') }} as flag_document_19,
        {{ to_bool_01('flag_document_20') }} as flag_document_20,
        {{ to_bool_01('flag_document_21') }} as flag_document_21,
        {{ to_bigint('amt_req_credit_bureau_hour') }} as amt_req_credit_bureau_hour,
        {{ to_bigint('amt_req_credit_bureau_day') }} as amt_req_credit_bureau_day,
        {{ to_bigint('amt_req_credit_bureau_week') }} as amt_req_credit_bureau_week,
        {{ to_bigint('amt_req_credit_bureau_mon') }} as amt_req_credit_bureau_mon,
        {{ to_bigint('amt_req_credit_bureau_qrt') }} as amt_req_credit_bureau_qrt,
        {{ to_bigint('amt_req_credit_bureau_year') }} as amt_req_credit_bureau_year,
        _loaded_at as loaded_at,
        _source_file as source_file
    from source

)

select * from typed
